DROP TABLE IF EXISTS customer CASCADE;
DROP TABLE IF EXISTS product CASCADE;
DROP TABLE IF EXISTS favourites CASCADE;
DROP TABLE IF EXISTS cart CASCADE;

DELETE FROM customer;
DELETE FROM product;
DELETE FROM favourites;
DELETE FROM cart;
