DROP TABLE IF EXISTS user CASCADE;
DROP TABLE IF EXISTS product CASCADE;
DROP TABLE IF EXISTS cart CASCADE;
DROP TABLE IF EXISTS cartitem CASCADE;

DELETE FROM users;
DELETE FROM product;
DELETE FROM cart;
DELETE FROM cartitem;
